name: Build Zola (indexing‑zh)

on:
  push:
    tags:        # 每打 tag 就编译一次，如 v0.18.0-zh1
      - 'v*'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          INSTALL_DIR="$GITHUB_WORKSPACE/dist"
          cargo install --locked --git https://github.com/getzola/zola --features "indexing-zh" --root "$INSTALL_DIR"
          # 打包
          tar -C "$INSTALL_DIR/bin" -czf zola-zh-linux-x86_64.tar.gz zola
          echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      # - name: Tar & upload
      #   run: |
      #     cd "$INSTALL_DIR/bin"
      #     tar -czf zola-zh-linux-x86_64.tar.gz zola
      #     echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          artifacts: "dist/bin/zola-zh-linux-x86_64.tar.gz"
          body: "Zola with indexing‑zh"
